version: "3.9"

services:
  cache:
    container_name: cache
    image: redis:alpine
    volumes:
      - ./trias-extractor/data:/data
    entrypoint: ["redis-server", "--appendonly", "yes"]

  trias-extractor:
    container_name: trias-extractor
    build:
      context: ./trias-extractor/
      dockerfile: Dockerfile.production
    environment:
      FLASK_ENV: production
    depends_on:
      - cache

  time-fc:
    container_name: time-fc
    build: ./time-fc/
    environment:
      FLASK_ENV: development
    depends_on:
      - cache

  weather-fc:
    container_name: weather-fc
    build: ./weather-fc
    environment:
      FLASK_ENV: development
    link:
      - owm_proxy

  owm_proxy:
    container_name: owm_proxy
    build: ./weather-fc/owm_proxy
    environment:
      FLASK_ENV: development
    depends_on:
      - weather-fc

  price-fc:
    container_name: price-fc
    build: ./price-fc
    environment:
      FLASK_ENV: production
    depends_on:
      - cache

  traffic-fc:
    container_name: traffic-fc
    build: ./traffic-fc
    environment:
      FLASK_ENV: production
    depends_on:
      - cache

  environmental-fc:
    container_name: environmental-fc
    build: ./environmental-fc
    environment:
      FLASK_ENV: production
    depends_on:
      - cache
      
  position-fc:
    container_name: position-fc
    build: ./position-fc
    environment:
      FLASK_ENV: production
    depends_on:
      - cache
      
  active-fc:
    container_name: active-fc
    build: ./active-fc
    environment:
      FLASK_ENV: production
    depends_on:
      - cache
      
  tsp-fc:
    container_name: tsp-fc
    build: ./tsp-fc
    environment:
      FLASK_ENV: production
    depends_on:
      - cache
      
  panoramic-fc:
    container_name: panoramic-fc
    build: ./panoramic-fc
    environment:
      FLASK_ENV: development
    depends_on:
      - cache

  oc-core:
    container_name: oc-core
    build: ./oc-core/
    environment:
      FLASK_ENV: development
    ports:
      - 5000:5000
    depends_on:
      - cache
    link:
      - trias-extractor
      - cache
      - active-fc
      - environmental-fc
      - panoramic-fc
      - position-fc
      - price-fc
      - time-fc
      - traffic-fc
      - tsp-fc
      - weather-fc
