version: "3.9"

services:
  trias-extractor:
    container_name: trias-extractor
    build:
      context: ./trias-extractor/
    # dockerfile: Dockerfile.production
    environment:
      FLASK_ENV: development
    ports:
      - "5001:5000"

  cache:
    container_name: cache
    image: "redis:alpine"
    volumes:
      - ./trias-extractor/data:/data
    entrypoint: ["redis-server", "--appendonly", "yes"]
    
  oc-core:
    container_name: oc-core
    build: ./oc-core/
    environment:
      FLASK_ENV: development
    volumes:
      - ./oc-core/oc-core.py:/code/oc-core.py
      - ./oc-core/oc-core.conf:/code/oc-core.conf
      - ./oc-core/determinant_factors.py:/code/determinant_factors.py
    ports:
      - "5000:5000"
    depends_on:
      - "cache"
      
  time-fc:
    container_name: time-fc
    build: ./time-fc/
    volumes:
       #we need to mount a single file, not to overwrite the whole folder
      - ./time-fc/time-fc.py:/code/time-fc.py
    environment:
      FLASK_ENV: development
    ports:
      - "5002:5000"
  
  weather-fc:
    container_name: weather-fc
    build: ./weather-fc/
    #volumes:
      #- ./weather-fc/weather.py:/code/weather.py
      # the next 2 lines should be removed when the Dockerfile is updated
      #- ./weather-fc/mapping:/code/mapping
      #- ./weather-fc/weather.conf:/code/weather.conf
    ports:
      - "5003:5000"
    environment:
      FLASK_ENV: development
      
  price-fc:
    container_name: price-fc
    build: ./price-fc/
    ports:
      - "5004:5000"
    environment:
      FLASK_ENV: development
      
  traffic-fc:
    container_name: traffic-fc
    build: ./traffic-fc
    ports:
      - "5005:5000"
    environment:
      FLASK_ENV: development
      
  enviromental-fc:
    container_name: enviromental-fc
    build: ./enviromental-fc
    ports:
      - "5006:5000"
    environment:
      FLASK_ENV: development
      
  position-fc:
    container_name: position-fc
    build: ./position-fc
    ports:
      - "5007:5000"
    environment:
      FLASK_ENV: development
      
  active-fc:
    container_name: active-fc
    build: ./active-fc
    ports:
      - "5008:5000"
    environment:
      FLASK_ENV: development
      
  tsp-fc:
    container_name: tsp-fc
    build: ./tsp-fc
    ports:
      - "5009:5000"
    environment:
      FLASK_ENV: development
      
  panoramic-fc:
    container_name: panoramic-fc
    build: ./panoramic-fc
    ports:
      - "5010:5000"
    environment:
      FLASK_ENV: development